import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const links = [
  { href: '/', label: 'Home' },
  { href: '/buttons', label: 'Buttons' },
  { href: '/size-space', label: 'Size & Space' },
  { href: '/modal', label: 'Modal' },
  { href: '/spacing', label: 'Spacing' },
  { href: '/form', label: 'Form' },
  { href: '/columns', label: 'Columns' },
  { href: '/flex', label: 'Flex' },
];

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
    <body className={inter.className}>
    <header className="border-b-2 border-black">
      <nav>
        <ul className="flex items-center">
          {links.map(({ label, href }) => (
            <li key={href} className="px-2 mr-2 text-m outline"><Link href={href}>{label}</Link></li>
          ))}
        </ul>
      </nav>
    </header>
    <main className="p-2">
      {children}
    </main>
    </body>
    </html>
  );
}
